# Generated by Django 5.0.3 on 2024-04-29 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='orders',
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(default='null.jpg', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='orders',
            name='orders',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.products'),
        ),
    ]
